# Generated by Django 5.2.4 on 2025-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, max_length=10, verbose_name='price')),
            ],
        ),
    ]
