
services:

  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app  # Montowanie aplikacji z lokalnego folderu
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - microservice-net
networks:
  microservice-net:
    external: true